#### general settings
name: Transformer_v0
model: video_base
distortion: sr
scale: 4
gpu_ids: [2,3]


#### datasets
datasets:
  train:
    name: Vimeo90K
    mode: Vimeo90K
    interval_list: [1]
    random_reverse: false
    border_mode: ~
    dataroot_GT: /home/lj/dzc/vimeo/vimeo90K_train_GT.lmdb
    dataroot_LQ: /home/lj/dzc/vimeo/vimeo90K_train_LR.lmdb
    
    cache_keys: ~
   
    N_frames: 7
    use_shuffle: true
    n_workers: 3
    batch_size: 8
    GT_size: 256
    LQ_size: 64
    use_flip: true
    use_rot: false
    color: RGB
  val:
    name: Vimeo90K
    mode: video_test
    dataroot_GT: /home/lj/dzc/vimeo/vimeo_septuplet/sequences
    dataroot_LQ: /home/lj/dzc/vimeo/vimeo_septuplet_matlabLRx4/sequences
    cache_data: ~
    N_frames: 7
    padding: new_info

#### network structures
network_G:
  which_model_G: Transformer_v0
  nf: 64
  nframes: 7
  groups: 7
  front_RBs: 5
  back_RBs: 10

#### path
path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~
  
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 6e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 300000
  ft_tsa_only: ~
  #ft_tsa_only: 50000
  warmup_iter: -1 # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
